spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      #ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/movie?useUnicode=yes&characterEncoding=UTF-8
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    sql-script-encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: "elvolver2@gmail.com"
    password: "ajsz xllm tchw uwbe"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  sql:
    init:
      encoding: UTF-8
  http:
    encoding: UTF-8
    enabled: true
  mandatory-file-encoding: UTF-8
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: client
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://volkovd.ru:8282/realms/main-realm
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          jwk-set-uri: http://volkovd.ru:8282/realms/main-realm/protocol/openid-connect/certs
          issuer-uri: http://volkovd.ru:8282/realms/main-realm

project:
  poster: posters/
  files: files/

external:
  resource:
    movies: "I:\\movies"
    posters: "I:\\movies\\posters"
    dir: "movies"
